language: node_js

node_js:
  - "node"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

# http://docs.travis-ci.com/user/database-setup/#RabbitMQ
services:
  - rabbitmq

# use --online so changes must apply to running broker
# https://www.rabbitmq.com/man/rabbitmq-plugins.1.man.html
before_script:
  - sudo rabbitmq-plugins enable --online rabbitmq_consistent_hash_exchange
